version: '3.7'

services:

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - compose-network
    ports:
      - 27017:27017
    volumes: 
      - ./data:/data/db

  mongo-express:
    container_name: mongo-express
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8181:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

    networks:
      - compose-network

networks:
  compose-network:
    name: compose-network
    driver: bridge